### ISSUE TITLE
bozuk link

### ISSUE THREAD

**Issue by srknhcgl** [vf-tech/linux_readdocs#3]
merhaba,
dokümanı okuyarak tek tek her bir adımı uygulamaya çalışıyorum.
http://software-dl.ti.com/processor-sdk-linux/esd/AM335X/latest/exports/ti-processor-sdk-linux-am335x-evm-05.03.00.07-Linux-x86-Install.bin linki çalışmadığı için ilerleyemedim. yardımcı olabilir misiniz?

**Comment by vf-tech** [comment]
merhaba

Aşağıdaki linki deneyebilir misin?

https://dr-download.ti.com/software-development/software-development-kit-sdk/MD-1BUptXj3op/05.03.00.07/ti-processor-sdk-linux-am335x-evm-05.03.00.07-Linux-x86-Install.bin
